### ISSUE TITLE
IPM Format  EBCDIC, RDW

### ISSUE THREAD

**Issue by Zellcl** [adelosa/cardutil#7]
Hi, i have a problem with a ipm file from mastercard, because the format of the file is distinct to the structure 1014 (EBCDIC, RDW), then the process indicates this error " line 165, in _iso8583_to_dict message_type_indicator, binary_bitmap, message_data = struct.unpack(struct.error: bad char in struct format".
There is another way to read a file with this EBCDIC structure?

**Comment by adelosa** [comment]
My understanding is RDW format is not 1014 blocked. Try adding the --no1014blocking option to your command and let me know how you go.. 
Otherwise you will need to provide more details so I can replicate the issue.

**Comment by Zellcl** [comment]
by adding the --no1014blocking option to the command gets an other error.

"C:\Users\gabriel.canales\Desktop\IPM>mci_ipm_to_csv --no1014blocking --in-encoding cp500 --out-encoding utf_8 4.ipm
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\mci_ipm_to_csv.exe\__main__.py", line 7, in <module>
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 10, in cli_entry
    cli_run(**vars(cli_parser().parse_args()))
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 22, in cli_run
    mci_ipm_to_csv(in_ipm=in_ipm, out_csv=out_csv, config=config, **kwargs)
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 79, in mci_ipm_to_csv
    dicts_to_csv(
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\cli\mci_ipm_to_csv.py", line 50, in dicts_to_csv
    for data_item in data_list:
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\mciipm.py", line 315, in __next__
    vbs_record = super(IpmReader, self).__next__()
  File "C:\Users\gabriel.canales\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\cardutil\mciipm.py", line 272, in __next__
    record = self.vbs_data.read(record_length)
ValueError: read length must be non-negative or -1"

so, what details you need to replicate the issue?

**Comment by adelosa** [comment]
The package documentation provides an overview of the 2 formats provided -- vbs and 1014 blocked. https://cardutil.readthedocs.io/en/latest/api.html#mastercard-file-formats 

Your file is neither. The issue looks like you are missing the record lengths (RDW) that precede each record.

For example, the start of your file is as follows (CP500 - this is hex, first 16 bytes)
`F1 F6 F4 F4   80 00 01 00   00 01 00 00   02 00 00 00    -- 1644 then bitmap.`
This should have a record length before the 1644 Mastercard MTI field.

If you are pulling these files off a mainframe using FTP, then it will tend to drop the RDW..
To force it to pass, you need to tell FTP to not drop them.
I think a site command like this is what will fix it.
https://www.ibm.com/docs/en/zos/2.2.0?topic=protocol-rdw-ftp-client-server-statement

Let me know how you go.

**Comment by Zellcl** [comment]
after raising the problem with mastercard, the problem with the ipm files, was the format sent, ,after correcting the files the process runs smoothly.
so thank´s a lot for your help! and keep up the good work with this project

**Comment by adelosa** [comment]
Hi @Zellcl. Thanks for the update
I am interested to know.. If the file you received was from Mastercard, is it a valid file format. If so, I can add support for that file type. Off the mainframe, variable length records without RDW are common but I was not aware this was an option available from mastercard. If so, can you tell me how they describe that file format so I can locate the manuals.

**Comment by Zellcl** [comment]
@adelosa , sorry for the delay in response.
mastercard explained to us, they exist for them 3 formats of IPM, that they can send to process.
formats are:
EBCDIC with RDW
EBCDIC without RDW
EBCDIC 1014

we currently work with the format EBCDIC 1014.

**Comment by ELNazerGit** [comment]
Hi All,

i tried the following CLI : `mci_ipm_param_to_csv.exe -o "TEST_ME.IP0040T1" --in-encoding cp037 --no1014blocking "MCI.AR.T067.B.E0000000.D260706.T083003.A001" IP0040T1 --config "\cardutil\cardutil.json" --expanded` 
but i am facing the following error:
`mci_ipm_param_to_csv (cardutil 0.7.3)
parameters:
 -in_filename:MCI.AR.T067.B.E0000000.D260706.T083003.A001
 -table_id:IP0040T1
 -out_filename:TEST_ME.IP0040T1
 -in_encoding:cp037
 -no1014blocking:True
 -expanded:True
 -config_file:cardutil\cardutil.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "mci_ipm_param_to_csv.exe\__main__.py", line 5, in <module>
    sys.exit(cli_entry())
             ~~~~~~~~~^^
  File "site-packages\cardutil\cli\mci_ipm_param_to_csv.py", line 10, in cli_entry
    cli_run(**vars(cli_parser().parse_args()))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages\cardutil\cli\mci_ipm_param_to_csv.py", line 27, in cli_run
    mci_ipm_param_to_csv(in_param=in_ipm, out_csv=out_csv, config=param_config, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages\cardutil\cli\mci_ipm_param_to_csv.py", line 61, in mci_ipm_param_to_csv
    vbs_in = mciipm.IpmParamReader(
        in_param,
    ...<4 lines>...
        expanded=expanded,
    )
  File "site-packages\cardutil\mciipm.py", line 426, in __init__
    vbs_record = super(IpmParamReader, self).__next__()
  File "site-packages\cardutil\mciipm.py", line 279, in __next__
    raise MciIpmDataError(f"Exceeded configured maximum VBS record length "
    ...<3 lines>...
                          binary_context_data=record_length_raw)
cardutil.mciipm.MciIpmDataError: Exceeded configured maximum VBS record length (6000) - value read was 4092916213`
File used attached 

[Files.zip](https://github.com/user-attachments/files/29936136/Files.zip)

**Comment by ELNazerGit** [comment]
> Hi, this is the ipm file i can´t decode with cardutil. [Test.zip](https://github.com/adelosa/cardutil/files/9021274/Test.zip) and the command i used is this. mci_ipm_to_csv --in-encoding cp500 --out-encoding utf_8 test.ipm or mci_ipm_to_csv --in-encoding cp500 --no1014blocking --out-encoding utf_8 test.ipm

Hi @Zellcl , can you send Full Updated T068 File
